---
apiVersion: v1
kind: Namespace
metadata:
  name: general-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: castsponsorskip
  namespace: general-services
  labels:
    app: castsponsorskip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: castsponsorskip
  template:
    metadata:
      labels:
        app: castsponsorskip
    spec:
      hostNetwork: true
      containers:
        - name: castsponsorskip
          image: ghcr.io/gabe565/castsponsorskip:latest 
---
apiVersion: v1
kind: Service
metadata:
  name: castsponsorskip-svc
  namespace: general-services
  labels:
    service: castsponsorskip
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: castsponsorskip
---
